### ISSUE TITLE
尝试在官方openwrt编译

### ISSUE THREAD

**Issue by moluanshanhe** [shiyunjin/koolshare-lede-fullcone#1]
尝试在官方openwrt22.03编译，请问大佬是编译https://github.com/fullcone-nat-nftables/nft-fullcone
这个吗？还需要做什么，谢谢！

**Comment by shiyunjin** [comment]
还需要根据你编译的时候里面的软件版本放到编译目录里面对应patch https://github.com/fullcone-nat-nftables （比如说里面的libnftl和nftables），只需要最上面的commit的patch就行
还得打这个patch https://github.com/fullcone-nat-nftables/openwrt-firewall4-with-fullcone

**Comment by moluanshanhe** [comment]
感谢您的回复
